enabled: true
production-mode: true
grid-size: grid-xl
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/feuerwehr-hungen/images/logo/logo_slim.png:
    name: logo_slim.png
    full_path: logo_slim.png
    type: image/png
    size: 32586
    path: user/themes/feuerwehr-hungen/images/logo/logo_slim.png
mobile_custom_logo:
  '-name': logo/logo_slim.png
custom_logo_mobile:
  user/themes/feuerwehr-hungen/images/logo/logo_slim.png:
    name: logo_slim.png
    full_path: logo_slim.png
    type: image/png
    size: 32586
    path: user/themes/feuerwehr-hungen/images/logo/logo_slim.png
