title: Grav
default_lang: de
author:
  name: 'Bastian Haaf'
  email: bastian@haaf.ch
taxonomies:
  - category
  - tag
  - month
metadata:
  description: 'Feuerwehr Hungen Inheiden, wir sind die örtliche Freiwillige Feuerwehr und zeigen euch gerne was bei uns passiert'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /ical: /user/pages/01.home/events.ics
routes:
  /something/else: /blog/focus-and-blur
  '/another/one/(.*)': /blog/$1
blog:
  route: ''
